# references:
# * http://www.objc.io/issue-6/travis-ci.html

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - git clone https://github.com/IBM-Swift/Package-Builder.git
      script: ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
    - os: osx
      osx_image: xcode9.2
      sudo: required
      language: objective-c
      env: TEST_DESTINATION="OS=11.2,name=iPhone 7"
      install:
        - ./install_swiftlint.sh
        - bundle install
      script:
        - bundle exec danger
        - set -o pipefail && xcodebuild test -workspace ViaSwiftUtils.xcworkspace -scheme ViaSwiftUtils_iOSTests -destination "$TEST_DESTINATION" | xcpretty
    - os: osx
      osx_image: xcode9.2
      sudo: required
      language: objective-c
      env: TEST_DESTINATION="OS=9.3,name=iPhone 6"
      install:
        - ./install_swiftlint.sh
        - bundle install
      script:
        - set -o pipefail && xcodebuild test -workspace ViaSwiftUtils.xcworkspace -scheme ViaSwiftUtils_iOSTests -destination "$TEST_DESTINATION" | xcpretty


cache: bundler
